#!/usr/bin/env python3
"""Build the single-file K230 CanMV vision UART script."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
DIST = ROOT / "dist"
OUT = DIST / "main_vision_uart_single.py"

MAIN_IMPORTS_TO_REMOVE = {
    "from transport.uart_publisher import VisionPublisher",
    "from vision.head_pose import HeadPoseDetector",
    "from vision.visual_observation import make_primary_face_observation",
}


def read(path):
    return path.read_text(encoding="utf-8")


def strip_uart_publisher_imports(text):
    marker = "class VisionPublisher:"
    index = text.index(marker)
    return text[index:].rstrip() + "\n"


def strip_head_pose_test_main(text):
    marker = "# ============ 测试代码 ============"
    return text.split(marker, 1)[0].rstrip() + "\n"


def strip_main_imports(text):
    lines = []
    for line in text.splitlines():
        if line in MAIN_IMPORTS_TO_REMOVE:
            continue
        lines.append(line)
    return "\n".join(lines).rstrip() + "\n"


def main():
    DIST.mkdir(parents=True, exist_ok=True)

    vision_protocol = read(SRC / "transport" / "vision_protocol.py").rstrip()
    uart_publisher = strip_uart_publisher_imports(
        read(SRC / "transport" / "uart_publisher.py")
    ).rstrip()
    visual_observation = read(SRC / "vision" / "visual_observation.py").rstrip()
    head_pose = strip_head_pose_test_main(
        read(SRC / "vision" / "head_pose.py")
    ).rstrip()
    main_vision_uart = strip_main_imports(
        read(SRC / "main_vision_uart.py")
    ).rstrip()

    output = f'''# Generated by tools/build_k230_single.py.
# Do not edit this file by hand. Edit files under src/ instead.

# ---- bundled src/transport/vision_protocol.py ----
{vision_protocol}


# ---- bundled src/transport/uart_publisher.py ----
{uart_publisher}


# ---- bundled src/vision/visual_observation.py ----
{visual_observation}


# ---- bundled src/vision/head_pose.py ----
{head_pose}


# ---- bundled src/main_vision_uart.py ----
{main_vision_uart}
'''
    OUT.write_text(output, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
